= Vert.x MySQL PostgreSQL client

image:https://vertx.ci.cloudbees.com/buildStatus/icon?job=vert.x3-mysql-postgresql-client["Build Status",link="https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-mysql-postgresql-client/"]


This Vert.x client uses the https://github.com/mauricio/postgresql-async[Mauricio Linhares driver] to support
a fully async client for MySQL and PostgreSQL.

Please see the in source asciidoc documentation or the main documentation on the web-site for a full description:

* Web-site docs
* link:src/main/asciidoc/java/index.adoc[Java in-source docs]
* link:src/main/asciidoc/js/index.adoc[JavaScript in-source docs]
* link:src/main/asciidoc/groovy/index.adoc[Groovy in-source docs]

== Requirements for running test suite

* A working PostgreSQL or MySQL server
* For testing PostgreSQL: A `testdb` database on a local PostgreSQL install and a user called `vertx` with password `password`
* For testing MySQL: A `testdb` database on a local MySQL install and a user called `vertx` with password `password`

Setting up test databases with Docker:

----
docker run --rm --name vertx-postgres -e POSTGRES_USER=vertx -e POSTGRES_PASSWORD=password -e POSTGRES_DB=testdb -p 5432:5432 postgres
----

----
docker run --rm --name vertx-mysql -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=vertx -e MYSQL_PASSWORD=password -e MYSQL_DATABASE=testdb -p 3306:3306 mysql/mysql-server:5.6
----
