= Vert.x MySQL / PostgreSQL client

The `link:jsdoc/async_sql_client-AsyncSQLClient.html[MySQL / PostgreSQL Client]` is responsible for providing an
interface for Vert.x applications that need to interact with a MySQL or PostgreSQL database.

It uses Mauricio Linhares https://github.com/mauricio/postgresql-async[open source driver] to interact with the MySQL
or PostgreSQL databases in a non blocking way

== Setting up the client

You can create an instance of the MySQL client as follows:

[source,java]
----
var MySQLClient = require("vertx-mysql-postgresql-js/my_sql_client");

var config = {
  "host" : "mymysqldb.mycompany"
};

var mySQLClient = MySQLClient.createMySQLClient(vertx, config);


----

Or the PostgreSQL client like this:

[source,java]
----
var PostgreSQLClient = require("vertx-mysql-postgresql-js/postgre_sql_client");

var config = {
  "host" : "mypostgresqldb.mycompany"
};

var postgreSQLClient = PostgreSQLClient.createPostgreSQLClient(vertx, config);

----

You can hold on to the client for a long time (e.g. the life-time of your verticle), but once you have finished with
it, you should close it using `link:jsdoc/async_sql_client-AsyncSQLClient.html#close[close]`

== Getting a connection

Use `link:jsdoc/async_sql_client-AsyncSQLClient.html#getConnection[getConnection]` to get a connection.

This will return the connection in the handler when one is ready from the pool.

* [source,java]
----

// Now do stuff with it:

service.getConnection(function (res, res_err) {
  if (res_err == null) {

    var connection = res;

    // Got a connection

  } else {
    // Failed to get connection - deal with it
  };
});


----

Once you've finished with the connection make sure you close it afterwards.

The connection is an instance of `link:../../vertx-sql-common/js/jsdoc/sql_connection-SQLConnection.html[SQLConnection]` which is a common interface used by
more than Vert.x sql service.

You can learn how to use it in the http://foobar[common sql interface] documentation.

=== Note about date and timestamps

Whenever you get dates back from the database, this service will implicitly convert them into ISO 8601
(`yyyy-MM-ddTHH:mm:ss.SSS`) formatted strings. MySQL usually discards milliseconds, so you will regularly see `.000`.

== Configuration

Both the PostgreSql and MySql services take the same configuration:

----
{
  "address" : <event-bus-address-to-listen-on>,
  "host" : <your-host>,
  "port" : <your-port>,
  "maxPoolSize" : <maximum-number-of-open-connections>,
  "username" : <your-username>,
  "password" : <your-password>,
  "database" : <name-of-your-database>
}
----

`address`:: The address this service should register on the event bus. Defaults to `vertx.postgresql` or `vertx.mysql`.
`host`:: The host of the database. Defaults to `localhost`.
`port`:: The port of the database. Defaults to `5432` for PostgreSQL and `3306` for MySQL.
`maxPoolSize`:: The number of connections that may be kept open. Defaults to `10`.
`username`:: The username to connect to the database. Defaults to `postgres` for PostgreSQL and `root` for MySQL.
`password`:: The password to connect to the database. Default is not set, i.e. it uses no password.
`database`:: The name of the database you want to connect to. Defaults to `test`.